version: '3.4'

networks:
  proxy:
    external:
      name: proxy_proxy

services:
  memoire_nginx:
    image: nginx:latest
    volumes:
      - "./src:/usr/share/nginx/html"
    networks:
      - proxy
    labels:
      com.dnsdock.alias: memoire.gouuv.docker
      com.dnsdock.ip_addr: "172.28.1.1"
      traefik.enable: "true"
      traefik.backend: memoire_nginx
      traefik.frontend.rule: "Host:memoire.gouuv.docker"
      traefik.docker.network: proxy_proxy
